version: "3.8"

name: racetracker-dev

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
