version: "3.8"

name: racetracker-local

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ../env
    networks:
      - racetracker-local
    volumes:
      - database-data:/var/lib/postgresql/data

  api:
    image: racetracker-oss/api
    ports:
      - 8080:8080
    env_file:
      - ../env
    depends_on:
      - database
    networks:
      - racetracker-local

networks:
  racetracker-local:
