version: "3.8"

name: racetracker-production

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD="r4c3tr4ck3r"
      - POSTGRES_USER="racetracker"
      - POSTGRES_DB="racetracker"
    networks:
      - racetracker-production

  api:
    image: floriian/racetracker-api:latest
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://racetracker:r4c3tr4ck3r@database:5432/racetracker?schema=public
      - ACCESS_TOKEN_SECRET=randomstring
      - PORT=8080
    depends_on:
      - database
    networks:
      - racetracker-production

networks:
  racetracker-production:

volumes:
  database-data:
